### ISSUE TITLE
from web its giving error

### ISSUE THREAD

**Issue by tarangshah19** [inouiw/capacitor-native-google-one-tap-signin#11]
when i try this with web its giving me follwing error 

Error: Assert error, expected '() => !!parentElem' to be true.
    at assert (helpers.ts:6:11)
    at GoogleOneTapAuth.renderSignInButton (GoogleOneTapAuth.ts:82:5)
    at async logIns (AuthProvider.vue:33:1)

But in android is working fin

**Comment by inouiw** [comment]
Hi @tarangshah19,

concerning `Error: Assert error, expected '() => !!parentElem' to be true.`.  The error is thrown if the element cannot be found. See `https://github.com/inouiw/capacitor-native-google-one-tap-signin/blob/a42e1dd4b111efadfff7db5400c6ecab25d4c227/src/GoogleOneTapAuth.ts#L82`
Since you are passing 'google-signin', ensure that `document.getElementById('google-signin')` returns an element and not undefined when calling `renderSignInButton`.

Concerning "But in android after 2 to 3 times auto login its not ask google id". Maybe you can describe in more detail what you mean. 
There was the issue https://github.com/inouiw/capacitor-native-google-one-tap-signin/issues/8 I fixed it but did not merge and create a new package yet. Will do that now. With the #8 Fix there is a new method `addSignInActionToExistingButton` that allows you to create your own Login button, and use this library to add a listener to it. You can reattach the listener if the promise is resolved.

Note that in the `/demo` folder there is a react demo project where you can see how to use the library.

**Comment by inouiw** [comment]
Version 5.1.0 is now published.

**Comment by inouiw** [comment]
Will close this issue. In case there is still a problem please reopen this issue or create a new one.
