### ISSUE TITLE
Signin button on Android stops working after signin cancelled

### ISSUE THREAD

**Issue by egranville** [inouiw/capacitor-native-google-one-tap-signin#4]
Hi David,

I'm sorry to bother you again. I have another question about the one tap signin (hopefully it's just something that I'm doing wrong).

The signin works well when the user is already signed in or uses the 'signin with google' button. But if the cancel the signin process then the signin button will not restart a signin when clicked and I get thin eeror in my console:

```
I/GoogleOneTapAuth Plugin: GoogleSignInClient.getSignInIntent not successful, statusCodeString Sign in action cancelled
    com.google.android.gms.common.api.ApiException: 12501: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.0.1:3)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(com.google.android.gms:play-services-auth@@20.4.1:3)
        at com.proventask.capacitor.GoogleOneTapAuth.GoogleOneTapAuth.googleSignInResultIntentCallback(GoogleOneTapAuth.java:267)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.Plugin.triggerActivityCallback(Plugin.java:155)
        at com.getcapacitor.Plugin.lambda$initializeActivityLaunchers$0$com-getcapacitor-Plugin(Plugin.java:117)
        at com.getcapacitor.Plugin$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:6)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:409)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:366)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:712)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:140)
        at com.getcapacitor.BridgeActivity.onActivityResult(BridgeActivity.java:173)
        at android.app.Activity.dispatchActivityResult(Activity.java:8327)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5009)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5057)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```
I tried but I don't seem to be able to catch this error in js to remove the old button and regenerate a new one.

Any ideas how we could solve this?

**Comment by inouiw** [comment]
Hi,
yes there is a bug.
When the button is clicked on android and then the user cancels and then clicks the button again, the native google authentication pop-up should appear again. The current behaviour is that clicking the button again does nothing.

I will try to fix it this weekend.
David

**Comment by egranville** [comment]
Thanks a lot!
Edward

**Comment by egranville** [comment]
Hi (@inouiw ) David,

Thanks for the fix!
